security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        GDdesign\UserBundle\Entity\UserRegister: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                require_previous_session: true
            logout: 
            anonymous:    true
            remember_me:
                 key: "%secret%"
                 name: BlogNewCookie
                 lifetime: 3600 # in seconds
                 path: /
                 domain: ~
                 secure: false
                 httponly: true
                 always_remember_me: false
                 remember_me_parameter: _remember_me

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/user/, role: ROLE_USER  }
