<?php

namespace GDdesign\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
     public function findByConversation($sender, $receiver)
    {
           return $this->getEntityManager()
				->createQuery('SELECT p
						 FROM GDdesignUserBundle:Message p
						 WHERE p.sender = :sender AND p.receiver = :receiver OR p.sender = :receiver AND p.receiver = :sender 
						')
				->setParameter('sender', $sender)
				->setParameter('receiver', $receiver)				
				->getResult();
    }
    public function findByUser($user)
    {
        return $this->getEntityManager()
				->createQuery('SELECT p
						 FROM GDdesignUserBundle:Message p
						 WHERE p.sender = :sender OR p.receiver = :receiver 
						 ORDER BY p.id DESC
						')
				->setParameter('sender', $user)
				->setParameter('receiver', $user)
				->getResult();
    }
   
    
  
	
	
}
