<?php

namespace GDdesign\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReplyRepository extends EntityRepository
{
  
    public function getAllContacts($limit)
    {
    	  return $this->getEntityManager()
    	  		  ->createQuery('SELECT q FROM GDdesignUserBundle:Reply  q WHERE q.id = 5 AND q.subject = :s  ORDER BY q.id LIMIT 10')
    	  		  ->setParameter('s', 'algo')
    	  		  ->getResult();
    }
	
	
}
